//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class coupon
    {
        public int couponid { get; set; }
        public Nullable<int> venderid { get; set; }
        public string coupon_name { get; set; }
        public string coupon_code { get; set; }
        public Nullable<int> coupon_type { get; set; }
        public Nullable<System.DateTime> coupon_valid_start_date { get; set; }
        public Nullable<System.DateTime> coupon_valid_end_date { get; set; }
        public string coupon_description { get; set; }
        public Nullable<bool> coupon_status { get; set; }
        public Nullable<double> discount { get; set; }
        public string condition { get; set; }
    
        public virtual vender vender { get; set; }
    }
}
