//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cust_notification
    {
        public int id { get; set; }
        public Nullable<int> customerid { get; set; }
        public Nullable<bool> from_thiban { get; set; }
        public Nullable<bool> changes_to_acc { get; set; }
        public Nullable<bool> coupon_alerts { get; set; }
        public Nullable<bool> feature_updates { get; set; }
    }
}
