//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerdefaultaddress
    {
        public int addressid { get; set; }
        public Nullable<int> custid { get; set; }
        public string custnote1 { get; set; }
        public string customernote2 { get; set; }
        public string streetaddress { get; set; }
        public string city { get; set; }
        public Nullable<int> zip { get; set; }
        public string state { get; set; }
        public string country { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
