//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class customeraddressproof
    {
        public int addressid { get; set; }
        public Nullable<int> customerid { get; set; }
        public string addressproof { get; set; }
        public string addressimage { get; set; }
        public Nullable<int> Image { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual ImageFile ImageFile { get; set; }
    }
}
