//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerpaymentcard
    {
        public int id { get; set; }
        public Nullable<int> customerid { get; set; }
        public Nullable<int> card_number { get; set; }
        public Nullable<System.DateTime> card_expiry { get; set; }
        public string card_cvv { get; set; }
        public string card_type { get; set; }
        public Nullable<bool> card_status { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
