//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class driverlog
    {
        public int dlogid { get; set; }
        public Nullable<int> driver_id { get; set; }
        public Nullable<System.DateTime> login_date { get; set; }
        public Nullable<System.DateTime> logout { get; set; }
        public Nullable<int> online_time { get; set; }
    
        public virtual driver driver { get; set; }
    }
}
