//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class driverpayoutrequested
    {
        public int dpayoutid { get; set; }
        public Nullable<int> driver_id { get; set; }
        public Nullable<System.DateTime> request_date { get; set; }
        public Nullable<int> tran_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual driver driver { get; set; }
    }
}
