//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class driveraddressproff
    {
        public int daddressid { get; set; }
        public Nullable<int> driver_id { get; set; }
        public string address_proff { get; set; }
        public string address_image { get; set; }
        public Nullable<int> Image { get; set; }
    
        public virtual driver driver { get; set; }
        public virtual ImageFile ImageFile { get; set; }
    }
}
