//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class driverinventory
    {
        public int id { get; set; }
        public Nullable<int> driverid { get; set; }
        public Nullable<int> productid { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
        public Nullable<int> returnstock { get; set; }
    }
}
