//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class driverdefaultaddress
    {
        public int addressid { get; set; }
        public Nullable<int> driverid { get; set; }
        public string drivernote1 { get; set; }
        public string drivernote2 { get; set; }
        public string streetaddress { get; set; }
        public string city { get; set; }
        public Nullable<int> zip { get; set; }
        public string state { get; set; }
        public string country { get; set; }
    
        public virtual driver driver { get; set; }
    }
}
