//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class driverrating
    {
        public int drateid { get; set; }
        public Nullable<int> driver_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<int> orderid { get; set; }
        public Nullable<System.DateTime> rating_date { get; set; }
        public string comment { get; set; }
        public string status { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual driver driver { get; set; }
        public virtual order order { get; set; }
    }
}
