//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class driverworkinghour
    {
        public int id { get; set; }
        public Nullable<int> driver_id { get; set; }
        public Nullable<int> working_hours_mondey { get; set; }
        public Nullable<int> working_hours_tuesday { get; set; }
        public Nullable<int> working_hours_wednesday { get; set; }
        public Nullable<int> working_hours_thursday { get; set; }
        public Nullable<int> working_hour_friday { get; set; }
        public Nullable<int> working_hour_saturday { get; set; }
        public Nullable<int> working_hour_sunday { get; set; }
    
        public virtual driver driver { get; set; }
    }
}
