//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class national_address
    {
        public int addressid { get; set; }
        public string buildingnumber { get; set; }
        public string streetname { get; set; }
        public string neighborhood { get; set; }
        public string city { get; set; }
        public Nullable<int> postal_zip_code { get; set; }
        public string district { get; set; }
        public Nullable<int> additionalnumber { get; set; }
        public Nullable<int> customerid { get; set; }
        public string address_type { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
