//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class onspotsale
    {
        public int onspotsaleid { get; set; }
        public Nullable<int> driverid { get; set; }
        public Nullable<int> trukid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> onspotqty { get; set; }
        public Nullable<decimal> onspotprice { get; set; }
        public Nullable<int> totalqty { get; set; }
        public Nullable<decimal> totalprice { get; set; }
        public Nullable<int> available { get; set; }
        public Nullable<decimal> onsopt_sale_latitude { get; set; }
        public Nullable<decimal> onspot_sale_longitude { get; set; }
        public Nullable<int> geofence { get; set; }
        public Nullable<int> total_inventory { get; set; }
        public Nullable<decimal> total_inventory_price { get; set; }
        public Nullable<int> available_inventory { get; set; }
        public Nullable<int> orderid { get; set; }
        public Nullable<int> productid { get; set; }
        public Nullable<int> shift_id { get; set; }
    
        public virtual driver driver { get; set; }
        public virtual order order { get; set; }
    }
}
