//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdeliveryweather
    {
        public int orderdeliveryweather_id { get; set; }
        public Nullable<int> driverid { get; set; }
        public Nullable<int> orderid { get; set; }
        public string weathertemp { get; set; }
        public string weatherhumidity { get; set; }
        public string weatherpressure { get; set; }
        public string weather_temp_max { get; set; }
        public string weather_temp_min { get; set; }
        public Nullable<System.DateTime> weathertime { get; set; }
        public string wind { get; set; }
        public string rain { get; set; }
    
        public virtual driver driver { get; set; }
    }
}
