//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.driverratings = new HashSet<driverrating>();
            this.oredercanclefeedbacks = new HashSet<oredercanclefeedback>();
            this.productrattings = new HashSet<productratting>();
            this.shippingaddresses = new HashSet<shippingaddress>();
            this.shippinghistories = new HashSet<shippinghistory>();
            this.onspotsales = new HashSet<onspotsale>();
        }
    
        public int orderid { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string ship_address { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> ship_date { get; set; }
        public string order_type { get; set; }
        public Nullable<System.DateTime> expected_delivery_time { get; set; }
        public Nullable<int> couponid { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> total { get; set; }
        public string bill_address { get; set; }
        public Nullable<bool> paid { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public string payment_type { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public Nullable<int> createdby { get; set; }
        public string status { get; set; }
        public string address_type { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<driverrating> driverratings { get; set; }
        public virtual product product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oredercanclefeedback> oredercanclefeedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productratting> productrattings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shippingaddress> shippingaddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shippinghistory> shippinghistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<onspotsale> onspotsales { get; set; }
    }
}
