//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class pandetail
    {
        public int panid { get; set; }
        public string pancardno { get; set; }
        public Nullable<int> venderid { get; set; }
        public string pan_image { get; set; }
        public Nullable<int> Image { get; set; }
    
        public virtual ImageFile ImageFile { get; set; }
        public virtual vender vender { get; set; }
    }
}
