//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class payoutall
    {
        public int dpayallid { get; set; }
        public Nullable<int> driver_id { get; set; }
        public Nullable<System.DateTime> transaction_date { get; set; }
        public Nullable<int> transaction_id { get; set; }
        public string payment_mode { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> adjustment_amount { get; set; }
        public Nullable<decimal> net_amount { get; set; }
    
        public virtual driver driver { get; set; }
    }
}
