//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.customerfavoriteproducts = new HashSet<customerfavoriteproduct>();
            this.orders = new HashSet<order>();
            this.productrattings = new HashSet<productratting>();
        }
    
        public int productid { get; set; }
        public Nullable<int> vender_id { get; set; }
        public string product_title { get; set; }
        public string brand { get; set; }
        public string description { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<decimal> customer_price { get; set; }
        public Nullable<int> customer_min_order_quantity { get; set; }
        public Nullable<int> customer_max_order_quantity { get; set; }
        public Nullable<decimal> store_price { get; set; }
        public Nullable<int> store_min_order_quantity { get; set; }
        public Nullable<int> store_max_order_quantity { get; set; }
        public string phno { get; set; }
        public Nullable<int> bottle_per_box { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<int> sku { get; set; }
        public Nullable<int> createdby { get; set; }
        public string status { get; set; }
        public string ProductAvaibility { get; set; }
        public string volume { get; set; }
        public Nullable<int> image { get; set; }
        public string bottle_material { get; set; }
        public string av_composition_ppm { get; set; }
        public string discount { get; set; }
        public string Image_path { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customerfavoriteproduct> customerfavoriteproducts { get; set; }
        public virtual ImageFile ImageFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
        public virtual vender vender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productratting> productrattings { get; set; }
    }
}
