//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class rolemanagement
    {
        public int id { get; set; }
        public Nullable<int> roleid { get; set; }
        public Nullable<int> menuid { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual role role { get; set; }
    }
}
