//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class shippinghistory
    {
        public int shiphistoryid { get; set; }
        public Nullable<int> driver_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<System.DateTime> reached_time { get; set; }
        public Nullable<System.DateTime> delivery_time { get; set; }
        public Nullable<int> wating_time { get; set; }
        public Nullable<int> delay_time { get; set; }
    
        public virtual driver driver { get; set; }
        public virtual order order { get; set; }
    }
}
