//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class storedetail
    {
        public int storeid { get; set; }
        public Nullable<int> venderid { get; set; }
        public string business_type { get; set; }
        public string language { get; set; }
        public string display_name { get; set; }
        public string reg_business_name { get; set; }
        public string business_address1 { get; set; }
        public string business_address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string warehouse_address1 { get; set; }
        public string warehouse_address2 { get; set; }
        public string Province { get; set; }
        public string RegistrationName { get; set; }
        public string WarehouseCity { get; set; }
        public string Bussinessofficehours { get; set; }
        public string WarehouseProvince { get; set; }
    
        public virtual vender vender { get; set; }
    }
}
