//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class teammanagement
    {
        public int memberid { get; set; }
        public string membername { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> vender_id { get; set; }
        public Nullable<int> roleid { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> creadteby { get; set; }
        public string member_type { get; set; }
    
        public virtual role role { get; set; }
        public virtual vender vender { get; set; }
    }
}
