//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vechicle
    {
        public int id { get; set; }
        public Nullable<int> driver_id { get; set; }
        public string vechicle_model { get; set; }
        public string vechicle_company_name { get; set; }
        public string vechicle_year { get; set; }
        public string vechicle_energy_type { get; set; }
        public Nullable<int> vechicle_cylender_type { get; set; }
        public Nullable<int> vechicle_fule_consumption_short { get; set; }
        public Nullable<int> vechicle_fule_consumption_long { get; set; }
        public Nullable<int> vechicle_assistant { get; set; }
        public Nullable<int> vechicle_max_capacity { get; set; }
        public Nullable<bool> vechicle_status { get; set; }
        public string vehicle_type { get; set; }
        public string plat_no { get; set; }
    
        public virtual driver driver { get; set; }
    }
}
