//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class venderpayoutrequested
    {
        public int vpayoutid { get; set; }
        public Nullable<int> venderid { get; set; }
        public Nullable<System.DateTime> requestdate { get; set; }
        public Nullable<int> transactionid { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual vender vender { get; set; }
    }
}
