//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class venderbankdetail
    {
        public int vender_bank_id { get; set; }
        public Nullable<int> venderid { get; set; }
        public int account_no { get; set; }
        public string benificary_name_in_bank { get; set; }
        public string bank_name { get; set; }
        public string branch_name { get; set; }
        public string ifsc_code { get; set; }
        public string benificary_name_in_bank_image { get; set; }
        public string HolderName { get; set; }
        public string IBANCode { get; set; }
        public string VatIdentityFicationNumber { get; set; }
        public string BankNameCaseOther { get; set; }
    
        public virtual vender vender { get; set; }
    }
}
