//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class venderaddressproof
    {
        public int vender_address_id { get; set; }
        public Nullable<int> venderid { get; set; }
        public string address_proof { get; set; }
        public string address_image { get; set; }
        public string CompanyTradeName { get; set; }
        public string CompanyType { get; set; }
        public string Nationality { get; set; }
        public string MainOffice { get; set; }
        public string PostalCode { get; set; }
        public string TlelphoneNumber { get; set; }
        public string RegistrationDate { get; set; }
        public string POBox { get; set; }
        public string CompanyType2 { get; set; }
        public string PanNumber { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> Image { get; set; }
    
        public virtual ImageFile ImageFile { get; set; }
        public virtual vender vender { get; set; }
    }
}
