//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_ThibanProject.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vender_zone_join
    {
        public int gid { get; set; }
        public Nullable<int> zoneid { get; set; }
        public Nullable<int> geofenceid { get; set; }
    }
}
